apiVersion: v1
kind: Service
metadata:
  name: libro-delete-service
spec:
  selector:
    app: libro-delete
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30085
  type: NodePort 